import type { Repo } from "./types";

export const STATIC_PROJECTS: Repo[] = [
  {
    id: 999001,
    name: "DogWalk",
    description:
      "Marketplace de serviços pet com autenticação, pagamentos e geolocalização — React, Supabase, Stripe e Cloudflare.",
    html_url: "",
    homepage: "https://seu.pet",
    stargazers_count: 0,
    forks_count: 0,
    language: "TypeScript",
    topics: ["featured", "web", "marketplace"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    hasDemo: true,
    icon: "🐾",
    imageUrl: "/projects/seu.pet.gif",
  },

  {
    id: 999003,
    name: "Portifolio",
    description:
      "Portfolio profissional estilo cockpit sci-fi — Next.js, Framer Motion, animações cinematográficas, tema ciano+preto.",
    html_url: "https://github.com/Samuelfmedeiros/Portifolio",
    homepage: "https://samuelmedeiros.vercel.app",
    stargazers_count: 0,
    forks_count: 0,
    language: "TypeScript",
    topics: ["featured", "web"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
    hasDemo: true,
    icon: "🚀",
    imageUrl: "/projects/portifolio.webp",
  },
  // Games — stay as static because they need gradients/icons
  {
    id: 1001,
    name: "simon-game",
    description:
      "Jogo clássico de memorização de sequência de cores. Repita a sequência para pontuar!",
    html_url: "https://github.com/Samuelfmedeiros/simon-game",
    homepage: "/games/simon-game/index.html",
    stargazers_count: 0,
    forks_count: 0,
    language: "JavaScript",
    topics: ["game", "react"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    hasDemo: false,
    icon: "🧠",
  },
  {
    id: 1002,
    name: "asteroid-dodge",
    description:
      "Jogo de desviar de asteroides. Controle a nave com o mouse e sobreviva o máximo possível!",
    html_url: "https://github.com/Samuelfmedeiros/asteroid-dodge",
    homepage: "/games/asteroid-dodge/index.html",
    stargazers_count: 0,
    forks_count: 0,
    language: "JavaScript",
    topics: ["game", "react"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
    hasDemo: false,
    icon: "🚀",
  },
  {
    id: 1003,
    name: "code-typing",
    description:
      "Desafio de digitação de código. Digite snippets de várias linguagens o mais rápido possível!",
    html_url: "https://github.com/Samuelfmedeiros/code-typing",
    homepage: "/games/code-typing/index.html",
    stargazers_count: 0,
    forks_count: 0,
    language: "JavaScript",
    topics: ["game", "react"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    hasDemo: false,
    icon: "⌨️",
  },
  {
    id: 1004,
    name: "memory-matrix",
    description:
      "Jogo de memória visual. Memorize as células destacadas e recrie o padrão!",
    html_url: "https://github.com/Samuelfmedeiros/memory-matrix",
    homepage: "/games/memory-matrix/index.html",
    stargazers_count: 0,
    forks_count: 0,
    language: "JavaScript",
    topics: ["game", "react"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #0d1117 0%, #161b22 50%, #21262d 100%)",
    hasDemo: false,
    icon: "🔲",
  },
  {
    id: 1005,
    name: "terminal",
    description:
      "Terminal interativo estilo shell — navegue pelo portfólio com comandos, easter eggs e temas retrô.",
    html_url: "https://github.com/Samuelfmedeiros/terminal",
    homepage: "/games/terminal/index.html",
    stargazers_count: 0,
    forks_count: 0,
    language: "TypeScript",
    topics: ["game", "react", "terminal"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 50%, #16213e 100%)",
    hasDemo: false,
    icon: "💻",
  },
];

export const FEATURED_PROJECTS = [
  "DogWalk",
  "Portifolio",
  "simon-game",
  "asteroid-dodge",
  "code-typing",
  "memory-matrix",
  "terminal",
];
export const GAME_PROJECTS = ["simon-game", "asteroid-dodge", "code-typing", "memory-matrix", "terminal"];
