var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/termos/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00~v27c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_09cw-jd.js")
R.c("server/chunks/ssr/[root-of-the-server]__07_irn~._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0o63vx3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__08.moxq._.js")
R.c("server/chunks/ssr/_0ettv.h._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0146g0y._.js")
R.c("server/chunks/ssr/src_0iqulvf._.js")
R.c("server/chunks/ssr/_0__m-8p._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_termos_page_actions_0bwk~my.js")
R.m(58492)
module.exports=R.m(58492).exports
